// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

package mcpproxy

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/golang-jwt/jwt/v5"
	"github.com/modelcontextprotocol/go-sdk/jsonrpc"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/stretchr/testify/require"

	"github.com/envoyproxy/ai-gateway/internal/filterapi"
	"github.com/envoyproxy/ai-gateway/internal/internalapi"
	"github.com/envoyproxy/ai-gateway/internal/json"
)

// modernBackendHandler builds an httptest handler that responds to modern
// (2026-07-28) JSON-RPC POST requests. It dispatches on the Mcp-Method header
// and returns a per-backend result generated by respFn, wrapped as a JSON-RPC
// success response. Backends listed in failBackends return a 500 so partial
// failure handling can be exercised.
func modernBackendHandler(t *testing.T, callCount *perBackendCallCount, failBackends map[string]bool, respFn func(backend, method string) any) http.Handler {
	t.Helper()
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		backend := r.Header.Get(internalapi.MCPBackendHeader)
		require.NotEmpty(t, backend, "backend header must be set on modern outbound request")
		method := r.Header.Get(mcpMethodHeader)
		require.Equal(t, protocolVersion20260728, r.Header.Get(mcpProtocolVersionHeader))
		if callCount != nil {
			callCount.inc(backend)
		}
		if failBackends[backend] {
			w.WriteHeader(http.StatusInternalServerError)
			_, _ = w.Write([]byte("backend down"))
			return
		}
		result := respFn(backend, method)
		// Echo the request id so sendModernRequest's id-match validation passes.
		id := json.RawMessage(`"1"`)
		if reqBody, err := io.ReadAll(r.Body); err == nil {
			var envelope struct {
				ID json.RawMessage `json:"id"`
			}
			if json.Unmarshal(reqBody, &envelope) == nil && len(envelope.ID) > 0 {
				id = envelope.ID
			}
		}
		body := map[string]any{"jsonrpc": "2.0", "id": id, "result": result}
		encoded, err := json.Marshal(body)
		require.NoError(t, err)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write(encoded)
	})
}

// newModernRequest builds an *http.Request carrying the modern headers that
// serveModernPOST validates before dispatching.
func newModernRequest(method string) *http.Request {
	r := httptest.NewRequest(http.MethodPost, "/mcp", nil)
	r.Header.Set(internalapi.MCPRouteHeader, "test-route")
	r.Header.Set(mcpMethodHeader, method)
	r.Header.Set(mcpProtocolVersionHeader, protocolVersion20260728)
	return r
}

func modernReq(t *testing.T, method string, params []byte) *jsonrpc.Request {
	t.Helper()
	id, err := jsonrpc.MakeID("1")
	require.NoError(t, err)
	return &jsonrpc.Request{ID: id, Method: method, Params: params}
}

// decodeResult decodes the JSON-RPC "result" object from a recorded response.
func decodeResult(t *testing.T, rr *httptest.ResponseRecorder) map[string]json.RawMessage {
	t.Helper()
	var envelope map[string]json.RawMessage
	require.NoError(t, json.Unmarshal(rr.Body.Bytes(), &envelope))
	require.Contains(t, envelope, "result")
	var result map[string]json.RawMessage
	require.NoError(t, json.Unmarshal(envelope["result"], &result))
	return result
}

// -----------------------------------------------------------------------------
// serveModernPOST validation / dispatch
// -----------------------------------------------------------------------------

func TestServeModernPOST_MissingRouteHeader(t *testing.T) {
	proxy := newTestMCPProxy()
	r := httptest.NewRequest(http.MethodPost, "/mcp", nil)
	rr := httptest.NewRecorder()
	req := modernReq(t, "tools/list", nil)

	proxy.serveModernPOST(rr, r, req, time.Now())

	require.Equal(t, http.StatusInternalServerError, rr.Code)
	require.Contains(t, rr.Body.String(), "missing route header")
}

func TestServeModernPOST_MethodHeaderMismatch(t *testing.T) {
	proxy := newTestMCPProxy()
	r := newModernRequest("tools/call")
	rr := httptest.NewRecorder()
	req := modernReq(t, "tools/list", nil)

	proxy.serveModernPOST(rr, r, req, time.Now())

	require.Equal(t, http.StatusBadRequest, rr.Code)
	require.Contains(t, rr.Body.String(), "does not match body method")
}

func TestServeModernPOST_RemovedMethods(t *testing.T) {
	for _, method := range []string{"initialize", "notifications/initialized", "ping", "logging/setLevel"} {
		t.Run(method, func(t *testing.T) {
			proxy := newTestMCPProxy()
			r := newModernRequest(method)
			rr := httptest.NewRecorder()
			req := modernReq(t, method, nil)

			proxy.serveModernPOST(rr, r, req, time.Now())

			require.Equal(t, http.StatusNotFound, rr.Code)
		})
	}
}

func TestServeModernPOST_UnknownMethod(t *testing.T) {
	proxy := newTestMCPProxy()
	r := newModernRequest("tools/frobnicate")
	rr := httptest.NewRecorder()
	req := modernReq(t, "tools/frobnicate", nil)

	proxy.serveModernPOST(rr, r, req, time.Now())

	require.Equal(t, http.StatusNotFound, rr.Code)
	require.Contains(t, rr.Body.String(), "unknown method")
}

func TestServeModernPOST_StartsSpanOnlyForSupportedMethods(t *testing.T) {
	// tools/call is not yet a modern-supported method; a span must not be
	// opened just because modernParamsForHeaderMetadata can parse it.
	t.Run("unknown method", func(t *testing.T) {
		tracer := &fakeTracer{}
		proxy := newTestMCPProxyWithTracer(tracer)
		r := newModernRequest("tools/call")
		rr := httptest.NewRecorder()
		req := modernReq(t, "tools/call", []byte(`{"name":"t"}`))

		proxy.serveModernPOST(rr, r, req, time.Now())

		require.Equal(t, http.StatusNotFound, rr.Code)
		require.Equal(t, 0, tracer.starts)
	})

	t.Run("removed method", func(t *testing.T) {
		tracer := &fakeTracer{}
		proxy := newTestMCPProxyWithTracer(tracer)
		r := newModernRequest("ping")
		rr := httptest.NewRecorder()
		req := modernReq(t, "ping", []byte(`{}`))

		proxy.serveModernPOST(rr, r, req, time.Now())

		require.Equal(t, http.StatusNotFound, rr.Code)
		require.Equal(t, 0, tracer.starts)
	})

	t.Run("supported method", func(t *testing.T) {
		respFn := func(_, _ string) any {
			return mcp.ListToolsResult{Tools: []*mcp.Tool{{Name: "t"}}}
		}
		server := httptest.NewServer(modernBackendHandler(t, nil, nil, respFn))
		defer server.Close()

		tracer := &fakeTracer{}
		proxy := newTestMCPProxyWithTracer(tracer)
		proxy.backendListenerAddr = server.URL
		delete(proxy.routes["test-route"].toolSelectors, "backend1")

		r := newModernRequest("tools/list")
		rr := httptest.NewRecorder()
		req := modernReq(t, "tools/list", []byte(`{}`))

		proxy.serveModernPOST(rr, r, req, time.Now())

		require.Equal(t, http.StatusOK, rr.Code, rr.Body.String())
		require.Equal(t, 1, tracer.starts)
		require.NotEmpty(t, tracer.span.backends)
		require.Len(t, tracer.span.listResults, 1)
	})
}

func TestServeModernPOST_InvalidParams(t *testing.T) {
	tracer := &fakeTracer{}
	proxy := newTestMCPProxyWithTracer(tracer)
	r := newModernRequest("tools/list")
	rr := httptest.NewRecorder()
	req := modernReq(t, "tools/list", []byte(`"not-an-object"`))

	proxy.serveModernPOST(rr, r, req, time.Now())

	require.Equal(t, http.StatusBadRequest, rr.Code)
	require.Contains(t, rr.Body.String(), "invalid params")
	require.Equal(t, 0, tracer.starts)
}

// TestServeModernPOST_DispatchFanout drives each fan-out method end-to-end
// through serveModernPOST against a live backend server.
func TestServeModernPOST_DispatchFanout(t *testing.T) {
	respFn := func(backend, method string) any {
		switch method {
		case "server/discover":
			return mcp.DiscoverResult{SupportedVersions: []string{protocolVersion20260728}, Capabilities: &mcp.ServerCapabilities{}}
		case "tools/list":
			return mcp.ListToolsResult{Tools: []*mcp.Tool{{Name: "t-" + backend}}}
		case "resources/list":
			return mcp.ListResourcesResult{Resources: []*mcp.Resource{{Name: "r-" + backend, URI: "file:///" + backend}}}
		case "resources/templates/list":
			return mcp.ListResourceTemplatesResult{ResourceTemplates: []*mcp.ResourceTemplate{{Name: "rt-" + backend, URITemplate: "file:///{x}"}}}
		case "prompts/list":
			return mcp.ListPromptsResult{Prompts: []*mcp.Prompt{{Name: "p-" + backend}}}
		}
		return map[string]any{}
	}

	for _, method := range []string{"server/discover", "tools/list", "resources/list", "resources/templates/list", "prompts/list"} {
		t.Run(method, func(t *testing.T) {
			server := httptest.NewServer(modernBackendHandler(t, nil, nil, respFn))
			defer server.Close()

			proxy := newTestMCPProxy()
			proxy.backendListenerAddr = server.URL
			// test-route has no tool selectors on backend2, but backend1 restricts to "test-tool".
			delete(proxy.routes["test-route"].toolSelectors, "backend1")

			r := newModernRequest(method)
			rr := httptest.NewRecorder()
			req := modernReq(t, method, nil)

			proxy.serveModernPOST(rr, r, req, time.Now())

			require.Equal(t, http.StatusOK, rr.Code, rr.Body.String())
			result := decodeResult(t, rr)
			require.Equal(t, `"complete"`, string(result["resultType"]))
			require.True(t, proxy.perBackendMetricsRecorded)
		})
	}
}

// -----------------------------------------------------------------------------
// handleServerDiscover
// -----------------------------------------------------------------------------

func TestHandleServerDiscover_RouteNotFound(t *testing.T) {
	proxy := newTestMCPProxy()
	rr := httptest.NewRecorder()
	req := modernReq(t, "server/discover", nil)

	_, err := proxy.handleServerDiscover(context.Background(), rr, req, "does-not-exist", nil)

	require.ErrorIs(t, err, errBackendNotFound)
	require.Equal(t, http.StatusNotFound, rr.Code)
}

func TestHandleServerDiscover_MergesBackends(t *testing.T) {
	callCount := &perBackendCallCount{}
	respFn := func(_, _ string) any {
		return mcp.DiscoverResult{SupportedVersions: []string{protocolVersion20260728}, Capabilities: &mcp.ServerCapabilities{Tools: &mcp.ToolCapabilities{}}}
	}
	server := httptest.NewServer(modernBackendHandler(t, callCount, nil, respFn))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	rr := httptest.NewRecorder()
	req := modernReq(t, "server/discover", nil)

	_, err := proxy.handleServerDiscover(context.Background(), rr, req, "test-route", nil)

	require.NoError(t, err)
	require.Equal(t, http.StatusOK, rr.Code)
	require.Equal(t, 1, callCount.get("backend1"))
	require.Equal(t, 1, callCount.get("backend2"))

	result := decodeResult(t, rr)
	require.Contains(t, result, "instructions")
	require.Contains(t, string(result["instructions"]), "aggregating 2 backends")
	require.JSONEq(t, `["2026-07-28"]`, string(result["supportedVersions"]))
	require.Equal(t, "0", string(result["ttlMs"]))
	require.Equal(t, `"public"`, string(result["cacheScope"]))
}

func TestHandleServerDiscover_PartialFailureStillMerges(t *testing.T) {
	respFn := func(_, _ string) any {
		return mcp.DiscoverResult{SupportedVersions: []string{protocolVersion20260728}, Capabilities: &mcp.ServerCapabilities{}}
	}
	server := httptest.NewServer(modernBackendHandler(t, nil, map[string]bool{"backend1": true}, respFn))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	rr := httptest.NewRecorder()
	req := modernReq(t, "server/discover", nil)

	_, err := proxy.handleServerDiscover(context.Background(), rr, req, "test-route", nil)

	require.NoError(t, err)
	require.Equal(t, http.StatusOK, rr.Code)
}

func TestHandleServerDiscover_AllBackendsFail(t *testing.T) {
	respFn := func(_, _ string) any { return mcp.DiscoverResult{} }
	server := httptest.NewServer(modernBackendHandler(t, nil, map[string]bool{"backend1": true, "backend2": true}, respFn))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	rr := httptest.NewRecorder()
	req := modernReq(t, "server/discover", nil)

	_, err := proxy.handleServerDiscover(context.Background(), rr, req, "test-route", nil)

	require.Error(t, err)
	require.Contains(t, err.Error(), "failed to discover any backend")
	require.Equal(t, http.StatusInternalServerError, rr.Code)
}

func jwtBackendSelectorAllowing(t *testing.T) *compiledAuthorization {
	t.Helper()
	return mustCompileBackendSelector(t, &filterapi.MCPRouteAuthorization{
		DefaultAction: filterapi.AuthorizationActionDeny,
		Rules: []filterapi.MCPRouteAuthorizationRule{
			{
				Action: filterapi.AuthorizationActionAllow,
				CEL:    new(`request.mcp.backend in request.auth.jwt.claims.mcp_backends`),
			},
		},
	})
}

func TestHandleServerDiscover_BackendSelectorFilters(t *testing.T) {
	callCount := &perBackendCallCount{}
	respFn := func(_, _ string) any {
		return mcp.DiscoverResult{SupportedVersions: []string{protocolVersion20260728}, Capabilities: &mcp.ServerCapabilities{}}
	}
	server := httptest.NewServer(modernBackendHandler(t, callCount, nil, respFn))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	proxy.routes["test-route"].backendSelector = jwtBackendSelectorAllowing(t)
	proxy.requestHeaders = http.Header{
		"Authorization": []string{"Bearer " + bearerTokenWithClaims(jwt.MapClaims{"mcp_backends": []string{"backend2"}})},
	}

	rr := httptest.NewRecorder()
	req := modernReq(t, "server/discover", nil)
	_, err := proxy.handleServerDiscover(context.Background(), rr, req, "test-route", nil)

	require.NoError(t, err)
	require.Equal(t, http.StatusOK, rr.Code)
	require.Equal(t, 0, callCount.get("backend1"))
	require.Equal(t, 1, callCount.get("backend2"))
	result := decodeResult(t, rr)
	require.Contains(t, string(result["instructions"]), "aggregating 1 backends")
}

func TestHandleModernToolsList_BackendSelectorFilters(t *testing.T) {
	callCount := &perBackendCallCount{}
	respFn := func(_, _ string) any {
		return mcp.ListToolsResult{Tools: []*mcp.Tool{{Name: "search"}}}
	}
	server := httptest.NewServer(modernBackendHandler(t, callCount, nil, respFn))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	delete(proxy.routes["test-route"].toolSelectors, "backend1")
	proxy.routes["test-route"].backendSelector = jwtBackendSelectorAllowing(t)

	token := bearerTokenWithClaims(jwt.MapClaims{"mcp_backends": []string{"backend2"}})
	r := newModernRequest("tools/list")
	r.Header.Set("Authorization", "Bearer "+token)
	rr := httptest.NewRecorder()
	req := modernReq(t, "tools/list", nil)

	_, err := proxy.handleModernToolsList(context.Background(), rr, r, req, "test-route", nil)
	require.NoError(t, err)
	require.Equal(t, http.StatusOK, rr.Code)
	require.Equal(t, 0, callCount.get("backend1"))
	require.Equal(t, 1, callCount.get("backend2"))

	result := decodeResult(t, rr)
	var tools struct {
		Tools []*mcp.Tool `json:"tools"`
	}
	require.NoError(t, json.Unmarshal(fmt.Appendf(nil, `{"tools":%s}`, result["tools"]), &tools))
	require.Len(t, tools.Tools, 1)
	require.Equal(t, downstreamResourceName("search", "backend2"), tools.Tools[0].Name)
}

func TestServeModernPOST_BackendSelectorDenied(t *testing.T) {
	proxy := newTestMCPProxy()
	proxy.routes["test-route"].backendSelector = mustCompileBackendSelector(t, &filterapi.MCPRouteAuthorization{
		DefaultAction: filterapi.AuthorizationActionDeny,
	})

	r := newModernRequest("tools/list")
	rr := httptest.NewRecorder()
	req := modernReq(t, "tools/list", nil)
	proxy.serveModernPOST(rr, r, req, time.Now())

	require.Equal(t, http.StatusForbidden, rr.Code)
	require.Equal(t, "access denied", rr.Body.String())
}

// -----------------------------------------------------------------------------
// handleModern*List fan-out handlers
// -----------------------------------------------------------------------------

func TestHandleModernToolsList_AggregatesAndPrefixes(t *testing.T) {
	respFn := func(backend, _ string) any {
		return mcp.ListToolsResult{Tools: []*mcp.Tool{{Name: "search"}, {Name: "other-" + backend}}}
	}
	server := httptest.NewServer(modernBackendHandler(t, nil, nil, respFn))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	// Remove backend1's selector so both backends' tools flow through.
	delete(proxy.routes["test-route"].toolSelectors, "backend1")

	r := newModernRequest("tools/list")
	rr := httptest.NewRecorder()
	req := modernReq(t, "tools/list", nil)

	_, err := proxy.handleModernToolsList(context.Background(), rr, r, req, "test-route", nil)
	require.NoError(t, err)
	require.Equal(t, http.StatusOK, rr.Code)

	result := decodeResult(t, rr)
	var tools struct {
		Tools []*mcp.Tool `json:"tools"`
	}
	require.NoError(t, json.Unmarshal(fmt.Appendf(nil, `{"tools":%s}`, result["tools"]), &tools))
	names := make([]string, 0, len(tools.Tools))
	for _, tl := range tools.Tools {
		names = append(names, tl.Name)
		require.Contains(t, tl.Name, nameSeparator)
	}
	require.Contains(t, names, downstreamResourceName("search", "backend1"))
	require.Contains(t, names, downstreamResourceName("search", "backend2"))
	require.Equal(t, "0", string(result["ttlMs"]))
	require.Equal(t, `"public"`, string(result["cacheScope"]))
}

func TestHandleModernToolsList_MergesCachingHints(t *testing.T) {
	respFn := func(backend, _ string) any {
		if backend == "backend1" {
			return mcp.ListToolsResult{
				Tools: []*mcp.Tool{{Name: "search"}},
				TTLMs: 2000, CacheScope: "public",
			}
		}
		return mcp.ListToolsResult{
			Tools: []*mcp.Tool{{Name: "search"}},
			TTLMs: 500, CacheScope: "private",
		}
	}
	server := httptest.NewServer(modernBackendHandler(t, nil, nil, respFn))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	delete(proxy.routes["test-route"].toolSelectors, "backend1")

	r := newModernRequest("tools/list")
	rr := httptest.NewRecorder()
	req := modernReq(t, "tools/list", nil)

	_, err := proxy.handleModernToolsList(context.Background(), rr, r, req, "test-route", nil)
	require.NoError(t, err)

	result := decodeResult(t, rr)
	require.Equal(t, "500", string(result["ttlMs"]))
	require.Equal(t, `"private"`, string(result["cacheScope"]))
}

func TestHandleModernToolsList_ToolSelectorFilters(t *testing.T) {
	respFn := func(_, _ string) any {
		return mcp.ListToolsResult{Tools: []*mcp.Tool{{Name: "test-tool"}, {Name: "blocked-tool"}}}
	}
	server := httptest.NewServer(modernBackendHandler(t, nil, nil, respFn))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	// backend1 selector only allows "test-tool"; backend2 has no selector so both pass.

	r := newModernRequest("tools/list")
	rr := httptest.NewRecorder()
	req := modernReq(t, "tools/list", nil)

	_, err := proxy.handleModernToolsList(context.Background(), rr, r, req, "test-route", nil)
	require.NoError(t, err)

	result := decodeResult(t, rr)
	var tools struct {
		Tools []*mcp.Tool `json:"tools"`
	}
	require.NoError(t, json.Unmarshal(fmt.Appendf(nil, `{"tools":%s}`, result["tools"]), &tools))
	names := make([]string, 0)
	for _, tl := range tools.Tools {
		names = append(names, tl.Name)
	}
	require.Contains(t, names, downstreamResourceName("test-tool", "backend1"))
	require.NotContains(t, names, downstreamResourceName("blocked-tool", "backend1"))
	require.Contains(t, names, downstreamResourceName("blocked-tool", "backend2"))
}

func TestHandleModernToolsList_RouteNotFound(t *testing.T) {
	proxy := newTestMCPProxy()
	r := newModernRequest("tools/list")
	rr := httptest.NewRecorder()
	req := modernReq(t, "tools/list", nil)

	_, err := proxy.handleModernToolsList(context.Background(), rr, r, req, "nope", nil)
	require.ErrorIs(t, err, errBackendNotFound)
	require.Equal(t, http.StatusNotFound, rr.Code)
}

func TestHandleModernResourcesList_AggregatesAndPrefixes(t *testing.T) {
	respFn := func(backend, _ string) any {
		return mcp.ListResourcesResult{Resources: []*mcp.Resource{{Name: "cfg", URI: "file:///etc/" + backend}}}
	}
	server := httptest.NewServer(modernBackendHandler(t, nil, nil, respFn))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	rr := httptest.NewRecorder()
	req := modernReq(t, "resources/list", nil)

	_, err := proxy.handleModernResourcesList(context.Background(), rr, newModernRequest("resources/list"), req, "test-route", nil)
	require.NoError(t, err)

	result := decodeResult(t, rr)
	var out struct {
		Resources []*mcp.Resource `json:"resources"`
	}
	require.NoError(t, json.Unmarshal(fmt.Appendf(nil, `{"resources":%s}`, result["resources"]), &out))
	require.Len(t, out.Resources, 2)
	names := []string{out.Resources[0].Name, out.Resources[1].Name}
	require.Contains(t, names, downstreamResourceName("cfg", "backend1"))
	require.Contains(t, names, downstreamResourceName("cfg", "backend2"))
}

func TestHandleModernResourcesList_RouteNotFound(t *testing.T) {
	proxy := newTestMCPProxy()
	rr := httptest.NewRecorder()
	req := modernReq(t, "resources/list", nil)
	_, err := proxy.handleModernResourcesList(context.Background(), rr, newModernRequest("resources/list"), req, "nope", nil)
	require.ErrorIs(t, err, errBackendNotFound)
	require.Equal(t, http.StatusNotFound, rr.Code)
}

func TestHandleModernResourceTemplatesList_Aggregates(t *testing.T) {
	respFn := func(_, _ string) any {
		return mcp.ListResourceTemplatesResult{ResourceTemplates: []*mcp.ResourceTemplate{{Name: "tmpl", URITemplate: "file:///{path}"}}}
	}
	server := httptest.NewServer(modernBackendHandler(t, nil, nil, respFn))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	rr := httptest.NewRecorder()
	req := modernReq(t, "resources/templates/list", nil)

	_, err := proxy.handleModernResourceTemplatesList(context.Background(), rr, newModernRequest("resources/templates/list"), req, "test-route", nil)
	require.NoError(t, err)

	result := decodeResult(t, rr)
	var out struct {
		ResourceTemplates []*mcp.ResourceTemplate `json:"resourceTemplates"`
	}
	require.NoError(t, json.Unmarshal(fmt.Appendf(nil, `{"resourceTemplates":%s}`, result["resourceTemplates"]), &out))
	require.Len(t, out.ResourceTemplates, 2)
}

func TestHandleModernResourceTemplatesList_RouteNotFound(t *testing.T) {
	proxy := newTestMCPProxy()
	rr := httptest.NewRecorder()
	req := modernReq(t, "resources/templates/list", nil)
	_, err := proxy.handleModernResourceTemplatesList(context.Background(), rr, newModernRequest("resources/templates/list"), req, "nope", nil)
	require.ErrorIs(t, err, errBackendNotFound)
	require.Equal(t, http.StatusNotFound, rr.Code)
}

func TestHandleModernPromptsList_Aggregates(t *testing.T) {
	respFn := func(_, _ string) any {
		return mcp.ListPromptsResult{Prompts: []*mcp.Prompt{{Name: "greet"}}}
	}
	server := httptest.NewServer(modernBackendHandler(t, nil, nil, respFn))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	rr := httptest.NewRecorder()
	req := modernReq(t, "prompts/list", nil)

	_, err := proxy.handleModernPromptsList(context.Background(), rr, newModernRequest("prompts/list"), req, "test-route", nil)
	require.NoError(t, err)

	result := decodeResult(t, rr)
	var out struct {
		Prompts []*mcp.Prompt `json:"prompts"`
	}
	require.NoError(t, json.Unmarshal(fmt.Appendf(nil, `{"prompts":%s}`, result["prompts"]), &out))
	require.Len(t, out.Prompts, 2)
	names := []string{out.Prompts[0].Name, out.Prompts[1].Name}
	require.Contains(t, names, downstreamResourceName("greet", "backend1"))
	require.Contains(t, names, downstreamResourceName("greet", "backend2"))
}

func TestHandleModernPromptsList_RouteNotFound(t *testing.T) {
	proxy := newTestMCPProxy()
	rr := httptest.NewRecorder()
	req := modernReq(t, "prompts/list", nil)
	_, err := proxy.handleModernPromptsList(context.Background(), rr, newModernRequest("prompts/list"), req, "nope", nil)
	require.ErrorIs(t, err, errBackendNotFound)
	require.Equal(t, http.StatusNotFound, rr.Code)
}

// -----------------------------------------------------------------------------
// sendToAllModernBackendsAndAggregateResponses partial / complete failure handling
// -----------------------------------------------------------------------------

func TestSendToAllModernBackends_PartialFailure(t *testing.T) {
	respFn := func(backend, _ string) any {
		return mcp.ListToolsResult{Tools: []*mcp.Tool{{Name: "t-" + backend}}}
	}
	server := httptest.NewServer(modernBackendHandler(t, nil, map[string]bool{"backend1": true}, respFn))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	proxy.requestHeaders = http.Header{}
	req := modernReq(t, "tools/list", nil)

	responses, err := sendToAllModernBackendsAndAggregateResponses[mcp.ListToolsResult](
		context.Background(), proxy, req, "test-route", proxy.routes["test-route"].backends, nil)
	require.NoError(t, err)
	require.Len(t, responses, 1)
	require.Equal(t, "backend2", responses[0].backendName)
}

func TestSendToAllModernBackends_UnmarshalFailureSkipped(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		backend := r.Header.Get(internalapi.MCPBackendHeader)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		if backend == "backend1" {
			// result is a string, cannot unmarshal into ListToolsResult.
			_, _ = w.Write([]byte(`{"jsonrpc":"2.0","id":"1","result":"not-an-object"}`))
			return
		}
		body := map[string]any{"jsonrpc": "2.0", "id": "1", "result": mcp.ListToolsResult{Tools: []*mcp.Tool{{Name: "ok"}}}}
		encoded, _ := json.Marshal(body)
		_, _ = w.Write(encoded)
	}))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	proxy.requestHeaders = http.Header{}
	req := modernReq(t, "tools/list", nil)

	responses, err := sendToAllModernBackendsAndAggregateResponses[mcp.ListToolsResult](
		context.Background(), proxy, req, "test-route", proxy.routes["test-route"].backends, nil)
	require.NoError(t, err)
	require.Len(t, responses, 1)
	require.Equal(t, "backend2", responses[0].backendName)
}

func TestSendToAllModernBackends_NoBackendsSelected(t *testing.T) {
	proxy := newTestMCPProxy()
	proxy.requestHeaders = http.Header{}
	req := modernReq(t, "tools/list", nil)

	responses, err := sendToAllModernBackendsAndAggregateResponses[mcp.ListToolsResult](
		context.Background(), proxy, req, "test-route", map[filterapi.MCPBackendName]filterapi.MCPBackend{}, nil)
	require.ErrorIs(t, err, errModernListNoBackends)
	require.Contains(t, err.Error(), "no backends selected")
	require.Nil(t, responses)
}

func TestHandleModernToolsList_PartialFailure(t *testing.T) {
	respFn := func(_, _ string) any {
		return mcp.ListToolsResult{Tools: []*mcp.Tool{{Name: "search"}}}
	}
	server := httptest.NewServer(modernBackendHandler(t, nil, map[string]bool{"backend1": true}, respFn))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	delete(proxy.routes["test-route"].toolSelectors, "backend1")
	delete(proxy.routes["test-route"].toolSelectors, "backend2")

	r := newModernRequest("tools/list")
	rr := httptest.NewRecorder()
	req := modernReq(t, "tools/list", nil)

	_, err := proxy.handleModernToolsList(context.Background(), rr, r, req, "test-route", nil)
	require.NoError(t, err)
	require.Equal(t, http.StatusOK, rr.Code)

	result := decodeResult(t, rr)
	var tools struct {
		Tools []*mcp.Tool `json:"tools"`
	}
	require.NoError(t, json.Unmarshal(fmt.Appendf(nil, `{"tools":%s}`, result["tools"]), &tools))
	require.Len(t, tools.Tools, 1)
	require.Equal(t, downstreamResourceName("search", "backend2"), tools.Tools[0].Name)
}

func TestHandleModernToolsList_AllBackendsFail(t *testing.T) {
	respFn := func(_, _ string) any {
		return mcp.ListToolsResult{Tools: []*mcp.Tool{{Name: "search"}}}
	}
	server := httptest.NewServer(modernBackendHandler(t, nil, map[string]bool{"backend1": true, "backend2": true}, respFn))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL

	r := newModernRequest("tools/list")
	rr := httptest.NewRecorder()
	req := modernReq(t, "tools/list", nil)

	_, err := proxy.handleModernToolsList(context.Background(), rr, r, req, "test-route", nil)
	require.ErrorIs(t, err, errModernListNoBackends)
	require.Equal(t, http.StatusInternalServerError, rr.Code)
}

// -----------------------------------------------------------------------------
// sendModernRequest
// -----------------------------------------------------------------------------

func TestSendModernRequest_PlainJSON(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		require.Equal(t, "application/json", r.Header.Get("Content-Type"))
		require.Equal(t, "backend1", r.Header.Get(internalapi.MCPBackendHeader))
		require.Equal(t, "test-route", r.Header.Get(internalapi.MCPRouteHeader))
		_, _ = w.Write([]byte(`{"jsonrpc":"2.0","id":"1","result":{"ok":true}}`))
	}))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	proxy.requestHeaders = http.Header{}
	req := modernReq(t, "tools/list", nil)

	raw, err := proxy.sendModernRequest(context.Background(), req, "test-route", proxy.routes["test-route"].backends["backend1"])
	require.NoError(t, err)
	require.JSONEq(t, `{"ok":true}`, string(raw))
}

func TestSendModernRequest_SSE(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/event-stream")
		_, _ = w.Write([]byte("event: message\ndata: {\"jsonrpc\":\"2.0\",\"id\":\"1\",\"result\":{\"sse\":true}}\n\n"))
	}))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	proxy.requestHeaders = http.Header{}
	req := modernReq(t, "tools/list", nil)

	raw, err := proxy.sendModernRequest(context.Background(), req, "test-route", proxy.routes["test-route"].backends["backend1"])
	require.NoError(t, err)
	require.JSONEq(t, `{"sse":true}`, string(raw))
}

func TestSendModernRequest_BackendError(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusBadGateway)
		_, _ = w.Write([]byte("upstream boom"))
	}))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	proxy.requestHeaders = http.Header{}
	req := modernReq(t, "tools/list", nil)

	_, err := proxy.sendModernRequest(context.Background(), req, "test-route", proxy.routes["test-route"].backends["backend1"])
	require.Error(t, err)
	require.Contains(t, err.Error(), "status 502")
}

func TestSendModernRequest_JSONRPCError(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write([]byte(`{"jsonrpc":"2.0","id":"1","error":{"code":-32000,"message":"bad"}}`))
	}))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	proxy.requestHeaders = http.Header{}
	req := modernReq(t, "tools/list", nil)

	_, err := proxy.sendModernRequest(context.Background(), req, "test-route", proxy.routes["test-route"].backends["backend1"])
	require.Error(t, err)
	require.Contains(t, err.Error(), "backend error")
}

func TestSendModernRequest_NoResult(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write([]byte(`{"jsonrpc":"2.0","id":"1","result":null}`))
	}))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	proxy.requestHeaders = http.Header{}
	req := modernReq(t, "tools/list", nil)

	_, err := proxy.sendModernRequest(context.Background(), req, "test-route", proxy.routes["test-route"].backends["backend1"])
	require.Error(t, err)
	require.Contains(t, err.Error(), "no result")
}

func TestSendModernRequest_IDMismatch(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write([]byte(`{"jsonrpc":"2.0","id":"other","result":{"ok":true}}`))
	}))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	proxy.requestHeaders = http.Header{}
	req := modernReq(t, "tools/list", nil)

	_, err := proxy.sendModernRequest(context.Background(), req, "test-route", proxy.routes["test-route"].backends["backend1"])
	require.Error(t, err)
	require.Contains(t, err.Error(), "response id mismatch")
}

func TestSendModernRequest_BothResultAndError(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write([]byte(`{"jsonrpc":"2.0","id":"1","result":{"ok":true},"error":{"code":-32000,"message":"bad"}}`))
	}))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	proxy.requestHeaders = http.Header{}
	req := modernReq(t, "tools/list", nil)

	_, err := proxy.sendModernRequest(context.Background(), req, "test-route", proxy.routes["test-route"].backends["backend1"])
	require.Error(t, err)
	require.Contains(t, err.Error(), "both result and error")
}

func TestSendModernRequest_MissingID(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		_, _ = w.Write([]byte(`{"jsonrpc":"2.0","result":{"ok":true}}`))
	}))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	proxy.requestHeaders = http.Header{}
	req := modernReq(t, "tools/list", nil)

	_, err := proxy.sendModernRequest(context.Background(), req, "test-route", proxy.routes["test-route"].backends["backend1"])
	require.Error(t, err)
	require.Contains(t, err.Error(), "missing id")
}

func TestSendModernRequest_ToolsCallMissingName(t *testing.T) {
	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = "http://unused"
	proxy.requestHeaders = http.Header{}
	req := modernReq(t, "tools/call", []byte(`{}`))

	_, err := proxy.sendModernRequest(context.Background(), req, "test-route", proxy.routes["test-route"].backends["backend1"])
	require.Error(t, err)
	require.Contains(t, err.Error(), "missing required name")
}

func TestSendModernRequest_ForwardsHeaders(t *testing.T) {
	var gotHeader string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotHeader = r.Header.Get("X-Fwd")
		_, _ = w.Write([]byte(`{"jsonrpc":"2.0","id":"1","result":{}}`))
	}))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	proxy.requestHeaders = http.Header{"X-Fwd": []string{"v1"}}
	proxy.routes["test-route"].forwardHeaders = []string{"X-Fwd"}
	req := modernReq(t, "tools/list", nil)

	_, err := proxy.sendModernRequest(context.Background(), req, "test-route", proxy.routes["test-route"].backends["backend1"])
	require.NoError(t, err)
	require.Equal(t, "v1", gotHeader)
}

func TestResolveModernRouteBackends_ExtractsForwardHeaders(t *testing.T) {
	proxy := newTestMCPProxy()
	proxy.requestHeaders = http.Header{
		"X-Fwd":         []string{"route-val"},
		"Authorization": []string{"Bearer tok"},
		"X-Only-B1":     []string{"b1-secret"},
	}
	proxy.routes["test-route"].forwardHeaders = []string{"X-Fwd"}
	b1 := proxy.routes["test-route"].backends["backend1"]
	b1.ForwardHeaders = []filterapi.MCPHeaderForward{
		{Name: "Authorization", BackendHeader: "X-Original-Auth"},
		{Name: "X-Only-B1"},
	}
	proxy.routes["test-route"].backends["backend1"] = b1
	b2 := proxy.routes["test-route"].backends["backend2"]
	b2.ForwardHeaders = []filterapi.MCPHeaderForward{
		{Name: "Authorization", BackendHeader: "X-Original-Auth"},
	}
	proxy.routes["test-route"].backends["backend2"] = b2

	rr := httptest.NewRecorder()
	_, selected, err := proxy.resolveModernRouteBackends(rr, "test-route")
	require.NoError(t, err)
	require.Contains(t, selected, "backend1")
	require.Contains(t, selected, "backend2")
	require.Equal(t, "route-val", proxy.extraHeaders["X-Fwd"])
	require.Equal(t, "Bearer tok", proxy.perBackendExtraHeaders["backend1"]["X-Original-Auth"])
	require.Equal(t, "b1-secret", proxy.perBackendExtraHeaders["backend1"]["X-Only-B1"])
	require.Equal(t, "Bearer tok", proxy.perBackendExtraHeaders["backend2"]["X-Original-Auth"])
	require.NotContains(t, proxy.perBackendExtraHeaders["backend2"], "X-Only-B1")
	require.True(t, proxy.forwardHeadersResolved)
}

func TestSendModernRequest_ForwardsPerBackendHeadersAfterResolve(t *testing.T) {
	var gotRoute, gotRenamed, gotB1Only string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotRoute = r.Header.Get("X-Fwd")
		gotRenamed = r.Header.Get("X-Original-Auth")
		gotB1Only = r.Header.Get("X-Only-B1")
		_, _ = w.Write([]byte(`{"jsonrpc":"2.0","id":"1","result":{}}`))
	}))
	defer server.Close()

	proxy := newTestMCPProxy()
	proxy.backendListenerAddr = server.URL
	proxy.requestHeaders = http.Header{
		"X-Fwd":         []string{"route-val"},
		"Authorization": []string{"Bearer tok"},
		"X-Only-B1":     []string{"b1-secret"},
	}
	proxy.routes["test-route"].forwardHeaders = []string{"X-Fwd"}
	b1 := proxy.routes["test-route"].backends["backend1"]
	b1.ForwardHeaders = []filterapi.MCPHeaderForward{
		{Name: "Authorization", BackendHeader: "X-Original-Auth"},
		{Name: "X-Only-B1"},
	}
	proxy.routes["test-route"].backends["backend1"] = b1

	rr := httptest.NewRecorder()
	_, _, err := proxy.resolveModernRouteBackends(rr, "test-route")
	require.NoError(t, err)

	req := modernReq(t, "tools/list", nil)
	_, err = proxy.sendModernRequest(context.Background(), req, "test-route", proxy.routes["test-route"].backends["backend1"])
	require.NoError(t, err)
	require.Equal(t, "route-val", gotRoute)
	require.Equal(t, "Bearer tok", gotRenamed)
	require.Equal(t, "b1-secret", gotB1Only)
}

func TestResolveModernRouteBackends_PerBackendHeadersOnlyForSelected(t *testing.T) {
	proxy := newTestMCPProxy()
	proxy.routes["test-route"].backendSelector = jwtBackendSelectorAllowing(t)
	proxy.requestHeaders = http.Header{
		"Authorization": []string{"Bearer " + bearerTokenWithClaims(jwt.MapClaims{"mcp_backends": []string{"backend2"}})},
		"X-B1":          []string{"secret-b1"},
		"X-B2":          []string{"secret-b2"},
	}
	b1 := proxy.routes["test-route"].backends["backend1"]
	b1.ForwardHeaders = []filterapi.MCPHeaderForward{{Name: "X-B1"}}
	proxy.routes["test-route"].backends["backend1"] = b1
	b2 := proxy.routes["test-route"].backends["backend2"]
	b2.ForwardHeaders = []filterapi.MCPHeaderForward{{Name: "X-B2"}}
	proxy.routes["test-route"].backends["backend2"] = b2

	rr := httptest.NewRecorder()
	_, selected, err := proxy.resolveModernRouteBackends(rr, "test-route")
	require.NoError(t, err)
	require.Equal(t, map[filterapi.MCPBackendName]filterapi.MCPBackend{"backend2": b2}, selected)
	require.NotContains(t, proxy.perBackendExtraHeaders, "backend1")
	require.Equal(t, "secret-b2", proxy.perBackendExtraHeaders["backend2"]["X-B2"])
}

// -----------------------------------------------------------------------------
// Pure helpers
// -----------------------------------------------------------------------------

func TestExtractJSONFromSSE(t *testing.T) {
	require.Nil(t, extractJSONFromSSE([]byte("event: ping\n\n")))
	require.Nil(t, extractJSONFromSSE([]byte("data: [DONE]\n")))
	got := extractJSONFromSSE([]byte("data: {\"a\":1}\ndata: {\"b\":2}\n"))
	require.JSONEq(t, `{"b":2}`, string(got))
}

func TestExtractNameForMethod(t *testing.T) {
	require.Empty(t, extractNameForMethod("tools/call", nil))
	require.Equal(t, "mytool", extractNameForMethod("tools/call", []byte(`{"name":"mytool"}`)))
	require.Equal(t, "myprompt", extractNameForMethod("prompts/get", []byte(`{"name":"myprompt"}`)))
	require.Equal(t, "file:///x", extractNameForMethod("resources/read", []byte(`{"uri":"file:///x"}`)))
	require.Empty(t, extractNameForMethod("tools/list", []byte(`{"name":"x"}`)))
}

func TestModernParamsForHeaderMetadata(t *testing.T) {
	require.Nil(t, modernParamsForHeaderMetadata(nil))
	require.Nil(t, modernParamsForHeaderMetadata(&jsonrpc.Request{Method: "tools/list"}))

	p := modernParamsForHeaderMetadata(&jsonrpc.Request{Method: "tools/call", Params: []byte(`{"name":"t"}`)})
	require.NotNil(t, p)

	p = modernParamsForHeaderMetadata(&jsonrpc.Request{Method: "resources/read", Params: []byte(`{"uri":"file:///x"}`)})
	require.NotNil(t, p)

	p = modernParamsForHeaderMetadata(&jsonrpc.Request{Method: "resources/subscribe", Params: []byte(`{"uri":"file:///x"}`)})
	require.NotNil(t, p)

	p = modernParamsForHeaderMetadata(&jsonrpc.Request{Method: "resources/unsubscribe", Params: []byte(`{"uri":"file:///x"}`)})
	require.NotNil(t, p)
}

func TestMergeDiscoverResults(t *testing.T) {
	merged := mergeDiscoverResults(slog.Default(), []*mcp.DiscoverResult{
		{
			SupportedVersions: []string{protocolVersion20260728, protocolVersion20250618},
			Capabilities:      &mcp.ServerCapabilities{Tools: &mcp.ToolCapabilities{}},
			TTLMs:             2000, CacheScope: "public",
		},
		{
			SupportedVersions: []string{protocolVersion20250618},
			Capabilities:      &mcp.ServerCapabilities{Prompts: &mcp.PromptCapabilities{}},
			TTLMs:             500, CacheScope: "private",
		},
		nil,
	})
	// The negotiated version is min across backends (one backend only supports
	// 2025-06-18), floored at 2025-06-18 and capped at the client's 2026-07-28.
	require.Equal(t, []string{protocolVersion20250618}, merged.SupportedVersions)
	require.NotNil(t, merged.Capabilities.Tools)
	require.NotNil(t, merged.Capabilities.Prompts)
	require.Equal(t, 500, merged.TTLMs)
	require.Equal(t, "private", merged.CacheScope)
}

func TestMergedProtocolVersion(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name          string
		clientVersion string
		backends      []backendReportedVersions
		want          string
	}{
		{
			name:          "no backends returns floor",
			clientVersion: protocolVersion20260728,
			backends:      nil,
			want:          protocolVersion20250618,
		},
		{
			name:          "no backend versions falls back to floor",
			clientVersion: protocolVersion20260728,
			backends: []backendReportedVersions{
				{name: "b1", versions: []string{""}},
				{name: "b2"},
			},
			want: protocolVersion20250618,
		},
		{
			name:          "single backend version is used",
			clientVersion: protocolVersion20260728,
			backends: []backendReportedVersions{
				{name: "b1", versions: []string{"2025-11-05"}},
			},
			want: "2025-11-05",
		},
		{
			name:          "minimum version across backends",
			clientVersion: protocolVersion20260728,
			backends: []backendReportedVersions{
				{name: "b1", versions: []string{"2025-11-05"}},
				{name: "b2", versions: []string{protocolVersion20250618}},
			},
			want: protocolVersion20250618,
		},
		{
			name:          "empty version treated as unset",
			clientVersion: protocolVersion20260728,
			backends: []backendReportedVersions{
				{name: "b1", versions: []string{"2025-11-05"}},
				{name: "b2", versions: []string{""}},
			},
			want: "2025-11-05",
		},
		{
			name:          "all empty returns floor",
			clientVersion: protocolVersion20260728,
			backends: []backendReportedVersions{
				{name: "b1", versions: []string{""}},
				{name: "b2", versions: []string{""}},
			},
			want: protocolVersion20250618,
		},
		{
			name:          "client version caps the result",
			clientVersion: protocolVersion20250618,
			backends: []backendReportedVersions{
				{name: "b1", versions: []string{protocolVersion20260728}},
			},
			want: protocolVersion20250618,
		},
		{
			name:          "empty client version does not cap",
			clientVersion: "",
			backends: []backendReportedVersions{
				{name: "b1", versions: []string{protocolVersion20260728}},
			},
			want: protocolVersion20260728,
		},
		{
			// Case 3 from PR #2543: client below floor, backends above floor.
			// Floor wins; client is lifted.
			name:          "client below floor lifted to floor when backends above",
			clientVersion: "2024-11-05",
			backends: []backendReportedVersions{
				{name: "b1", versions: []string{protocolVersion20250618}},
				{name: "b2", versions: []string{protocolVersion20260728}},
			},
			want: protocolVersion20250618,
		},
		{
			name:          "client below floor lifted to floor with single backend at floor",
			clientVersion: "2024-11-05",
			backends: []backendReportedVersions{
				{name: "b1", versions: []string{protocolVersion20250618}},
			},
			want: protocolVersion20250618,
		},
		{
			name:          "client below floor lifted to floor with backend above",
			clientVersion: "2024-11-05",
			backends: []backendReportedVersions{
				{name: "b1", versions: []string{protocolVersion20260728}},
			},
			want: protocolVersion20250618,
		},
		{
			// Case 2 from PR #2543: backend below floor is lifted.
			name:          "backend below floor lifted to floor",
			clientVersion: protocolVersion20250618,
			backends: []backendReportedVersions{
				{name: "b1", versions: []string{"2024-11-05"}},
				{name: "b2", versions: []string{"2025-11-25"}},
			},
			want: protocolVersion20250618,
		},
		{
			name:          "all above floor keeps floor inert",
			clientVersion: protocolVersion20260728,
			backends: []backendReportedVersions{
				{name: "b1", versions: []string{protocolVersion20260728}},
			},
			want: protocolVersion20260728,
		},
		{
			name:          "per-backend max is used before taking min",
			clientVersion: protocolVersion20260728,
			backends: []backendReportedVersions{
				{name: "b1", versions: []string{protocolVersion20250618, protocolVersion20260728}},
			},
			want: protocolVersion20260728,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			got := mergedProtocolVersion(slog.Default(), tt.clientVersion, tt.backends)
			require.Equal(t, tt.want, got)
		})
	}
}

func TestSessionMergedProtocolVersion(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name          string
		backends      map[filterapi.MCPBackendName]*compositeSessionEntry
		clientVersion string
		want          string
	}{
		{
			name:          "no backends returns floor",
			backends:      map[filterapi.MCPBackendName]*compositeSessionEntry{},
			clientVersion: protocolVersion20260728,
			want:          protocolVersion20250618,
		},
		{
			name: "single backend version is used",
			backends: map[filterapi.MCPBackendName]*compositeSessionEntry{
				"b1": {protocolVersion: "2025-11-05"},
			},
			clientVersion: protocolVersion20260728,
			want:          "2025-11-05",
		},
		{
			name: "minimum version across backends",
			backends: map[filterapi.MCPBackendName]*compositeSessionEntry{
				"b1": {protocolVersion: "2025-11-05"},
				"b2": {protocolVersion: protocolVersion20250618},
			},
			clientVersion: protocolVersion20260728,
			want:          protocolVersion20250618,
		},
		{
			name: "empty version treated as unset",
			backends: map[filterapi.MCPBackendName]*compositeSessionEntry{
				"b1": {protocolVersion: "2025-11-05"},
				"b2": {protocolVersion: ""},
			},
			clientVersion: protocolVersion20260728,
			want:          "2025-11-05",
		},
		{
			name: "all empty returns floor",
			backends: map[filterapi.MCPBackendName]*compositeSessionEntry{
				"b1": {protocolVersion: ""},
				"b2": {protocolVersion: ""},
			},
			clientVersion: protocolVersion20260728,
			want:          protocolVersion20250618,
		},
		{
			name: "client version caps the result",
			backends: map[filterapi.MCPBackendName]*compositeSessionEntry{
				"b1": {protocolVersion: protocolVersion20260728},
			},
			clientVersion: protocolVersion20250618,
			want:          protocolVersion20250618,
		},
		{
			name: "empty client version does not cap",
			backends: map[filterapi.MCPBackendName]*compositeSessionEntry{
				"b1": {protocolVersion: protocolVersion20260728},
			},
			clientVersion: "",
			want:          protocolVersion20260728,
		},
		{
			name: "client below floor lifted to floor when backends above",
			backends: map[filterapi.MCPBackendName]*compositeSessionEntry{
				"b1": {protocolVersion: protocolVersion20250618},
				"b2": {protocolVersion: protocolVersion20260728},
			},
			clientVersion: "2024-11-05",
			want:          protocolVersion20250618,
		},
		{
			name: "backend below floor lifted to floor",
			backends: map[filterapi.MCPBackendName]*compositeSessionEntry{
				"b1": {protocolVersion: "2024-11-05"},
				"b2": {protocolVersion: "2025-11-25"},
			},
			clientVersion: protocolVersion20250618,
			want:          protocolVersion20250618,
		},
		{
			name: "all above floor keeps floor inert",
			backends: map[filterapi.MCPBackendName]*compositeSessionEntry{
				"b1": {protocolVersion: protocolVersion20260728},
			},
			clientVersion: protocolVersion20260728,
			want:          protocolVersion20260728,
		},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			s := &session{perBackendSessions: tc.backends}
			got := s.mergedProtocolVersion(tc.clientVersion)
			require.Equal(t, tc.want, got)
		})
	}
}

// TestMergedProtocolVersion_FloorEngagedWarning asserts the floor-engaged
// warning fires when the floor lifts the negotiated version above what
// the client or a backend advertised.
func TestMergedProtocolVersion_FloorEngagedWarning(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name          string
		backends      map[filterapi.MCPBackendName]*compositeSessionEntry
		clientVersion string
		wantMerged    string
		wantLogSubstr []string
	}{
		{
			name: "client below floor logs client_requested and floor",
			backends: map[filterapi.MCPBackendName]*compositeSessionEntry{
				"b1": {protocolVersion: protocolVersion20250618},
				"b2": {protocolVersion: protocolVersion20260728},
			},
			clientVersion: "2024-11-05",
			wantMerged:    protocolVersion20250618,
			wantLogSubstr: []string{
				"MCP protocol version below floor",
				"client_requested=2024-11-05",
				"floor=" + protocolVersion20250618,
			},
		},
		{
			name: "backend below floor logs floored_backends",
			backends: map[filterapi.MCPBackendName]*compositeSessionEntry{
				"b1": {protocolVersion: "2024-11-05"},
				"b2": {protocolVersion: "2025-11-25"},
			},
			clientVersion: protocolVersion20250618,
			wantMerged:    protocolVersion20250618,
			wantLogSubstr: []string{
				"MCP protocol version below floor",
				"floored_backends=b1(2024-11-05)",
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			var buf bytes.Buffer
			s := &session{
				perBackendSessions: tc.backends,
				reqCtx: &mcpRequestContext{
					ProxyConfig: &ProxyConfig{
						l: slog.New(slog.NewTextHandler(&buf, nil)),
					},
				},
			}
			got := s.mergedProtocolVersion(tc.clientVersion)
			require.Equal(t, tc.wantMerged, got)
			logs := buf.String()
			for _, sub := range tc.wantLogSubstr {
				require.Contains(t, logs, sub, "expected log to contain %q; got:\n%s", sub, logs)
			}
		})
	}
}

func TestApplyMergedCachingHints(t *testing.T) {
	var dst mcp.Cacheable
	applyMergedCachingHints(&dst, []broadCastResponse[mcp.ListToolsResult]{
		{backendName: "b1", res: mcp.ListToolsResult{Cacheable: mcp.Cacheable{TTLMs: 2000, CacheScope: "public"}}},
		{backendName: "b2", res: mcp.ListToolsResult{Cacheable: mcp.Cacheable{TTLMs: 500, CacheScope: "private"}}},
	})
	require.Equal(t, 500, dst.TTLMs)
	require.Equal(t, "private", dst.CacheScope)
}

func TestMergeCachingHintsFromBackends(t *testing.T) {
	t.Run("empty defaults", func(t *testing.T) {
		ttlMs, scope := mergeCachingHintsFromBackends(nil)
		require.Equal(t, defaultTTLMs, ttlMs)
		require.Equal(t, defaultCacheScope, scope)
	})

	t.Run("positive ttl picks minimum", func(t *testing.T) {
		ttlMs, scope := mergeCachingHintsFromBackends([]mcp.Cacheable{
			{TTLMs: 2000, CacheScope: "public"},
			{TTLMs: 500, CacheScope: "public"},
		})
		require.Equal(t, 500, ttlMs)
		require.Equal(t, "public", scope)
	})

	t.Run("negative ttl clamped and scope tightened", func(t *testing.T) {
		ttlMs, scope := mergeCachingHintsFromBackends([]mcp.Cacheable{
			{TTLMs: -100, CacheScope: "public"},
			{TTLMs: 1500, CacheScope: "private"},
		})
		require.Equal(t, 0, ttlMs)
		require.Equal(t, "private", scope)
	})

	t.Run("empty cacheScope treated as public default", func(t *testing.T) {
		ttlMs, scope := mergeCachingHintsFromBackends([]mcp.Cacheable{
			{TTLMs: 1200},
			{TTLMs: 1500, CacheScope: "public"},
		})
		require.Equal(t, 1200, ttlMs)
		require.Equal(t, "public", scope)
	})
}

func TestDiscoverParams(t *testing.T) {
	var parsed map[string]json.RawMessage
	require.NoError(t, json.Unmarshal(discoverParams(), &parsed))
	require.Contains(t, parsed, "_meta")

	id, err := jsonrpc.MakeID("gw-discover-test")
	require.NoError(t, err)
	_, err = jsonrpc.EncodeMessage(&jsonrpc.Request{
		ID:     id,
		Method: "server/discover",
		Params: discoverParams(),
	})
	require.NoError(t, err)
}

func TestEnsureResultType(t *testing.T) {
	require.JSONEq(t, `{"resultType":"complete"}`, string(ensureResultType(nil)))
	require.JSONEq(t, `{"resultType":"complete","x":1}`, string(ensureResultType([]byte(`{"x":1}`))))
	// Already has resultType: left untouched.
	require.JSONEq(t, `{"resultType":"input_required"}`, string(ensureResultType([]byte(`{"resultType":"input_required"}`))))
	// Non-object JSON: returned as-is.
	require.Equal(t, `123`, string(ensureResultType([]byte(`123`))))
}

func TestWriteJSONRPCResult(t *testing.T) {
	rr := httptest.NewRecorder()
	id, err := jsonrpc.MakeID("42")
	require.NoError(t, err)
	writeJSONRPCResult(rr, id, map[string]any{"hello": "world"})

	require.Equal(t, http.StatusOK, rr.Code)
	require.Equal(t, "application/json", rr.Header().Get("Content-Type"))
	var envelope map[string]json.RawMessage
	require.NoError(t, json.Unmarshal(rr.Body.Bytes(), &envelope))
	require.Equal(t, `"2.0"`, string(envelope["jsonrpc"]))
	var result map[string]json.RawMessage
	require.NoError(t, json.Unmarshal(envelope["result"], &result))
	require.Equal(t, `"complete"`, string(result["resultType"]))
}
