// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	aigatewayapiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	versioned "github.com/envoyproxy/ai-gateway/api/v1alpha1/client/clientset/versioned"
	internalinterfaces "github.com/envoyproxy/ai-gateway/api/v1alpha1/client/informers/externalversions/internalinterfaces"
	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1/client/listers/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GuardrailPolicyInformer provides access to a shared informer and lister for
// GuardrailPolicies.
type GuardrailPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() apiv1alpha1.GuardrailPolicyLister
}

type guardrailPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGuardrailPolicyInformer constructs a new informer for GuardrailPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGuardrailPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGuardrailPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGuardrailPolicyInformer constructs a new informer for GuardrailPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGuardrailPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AigatewayV1alpha1().GuardrailPolicies(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AigatewayV1alpha1().GuardrailPolicies(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AigatewayV1alpha1().GuardrailPolicies(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AigatewayV1alpha1().GuardrailPolicies(namespace).Watch(ctx, options)
			},
		}, client),
		&aigatewayapiv1alpha1.GuardrailPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *guardrailPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGuardrailPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *guardrailPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&aigatewayapiv1alpha1.GuardrailPolicy{}, f.defaultInformer)
}

func (f *guardrailPolicyInformer) Lister() apiv1alpha1.GuardrailPolicyLister {
	return apiv1alpha1.NewGuardrailPolicyLister(f.Informer().GetIndexer())
}
