// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// GuardrailPolicyLister helps list GuardrailPolicies.
// All objects returned here must be treated as read-only.
type GuardrailPolicyLister interface {
	// List lists all GuardrailPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.GuardrailPolicy, err error)
	// GuardrailPolicies returns an object that can list and get GuardrailPolicies.
	GuardrailPolicies(namespace string) GuardrailPolicyNamespaceLister
	GuardrailPolicyListerExpansion
}

// guardrailPolicyLister implements the GuardrailPolicyLister interface.
type guardrailPolicyLister struct {
	listers.ResourceIndexer[*apiv1alpha1.GuardrailPolicy]
}

// NewGuardrailPolicyLister returns a new GuardrailPolicyLister.
func NewGuardrailPolicyLister(indexer cache.Indexer) GuardrailPolicyLister {
	return &guardrailPolicyLister{listers.New[*apiv1alpha1.GuardrailPolicy](indexer, apiv1alpha1.Resource("guardrailpolicy"))}
}

// GuardrailPolicies returns an object that can list and get GuardrailPolicies.
func (s *guardrailPolicyLister) GuardrailPolicies(namespace string) GuardrailPolicyNamespaceLister {
	return guardrailPolicyNamespaceLister{listers.NewNamespaced[*apiv1alpha1.GuardrailPolicy](s.ResourceIndexer, namespace)}
}

// GuardrailPolicyNamespaceLister helps list and get GuardrailPolicies.
// All objects returned here must be treated as read-only.
type GuardrailPolicyNamespaceLister interface {
	// List lists all GuardrailPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.GuardrailPolicy, err error)
	// Get retrieves the GuardrailPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.GuardrailPolicy, error)
	GuardrailPolicyNamespaceListerExpansion
}

// guardrailPolicyNamespaceLister implements the GuardrailPolicyNamespaceLister
// interface.
type guardrailPolicyNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.GuardrailPolicy]
}
