// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	scheme "github.com/envoyproxy/ai-gateway/api/v1alpha1/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GuardrailPoliciesGetter has a method to return a GuardrailPolicyInterface.
// A group's client should implement this interface.
type GuardrailPoliciesGetter interface {
	GuardrailPolicies(namespace string) GuardrailPolicyInterface
}

// GuardrailPolicyInterface has methods to work with GuardrailPolicy resources.
type GuardrailPolicyInterface interface {
	Create(ctx context.Context, guardrailPolicy *apiv1alpha1.GuardrailPolicy, opts v1.CreateOptions) (*apiv1alpha1.GuardrailPolicy, error)
	Update(ctx context.Context, guardrailPolicy *apiv1alpha1.GuardrailPolicy, opts v1.UpdateOptions) (*apiv1alpha1.GuardrailPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, guardrailPolicy *apiv1alpha1.GuardrailPolicy, opts v1.UpdateOptions) (*apiv1alpha1.GuardrailPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.GuardrailPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.GuardrailPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.GuardrailPolicy, err error)
	GuardrailPolicyExpansion
}

// guardrailPolicies implements GuardrailPolicyInterface
type guardrailPolicies struct {
	*gentype.ClientWithList[*apiv1alpha1.GuardrailPolicy, *apiv1alpha1.GuardrailPolicyList]
}

// newGuardrailPolicies returns a GuardrailPolicies
func newGuardrailPolicies(c *AigatewayV1alpha1Client, namespace string) *guardrailPolicies {
	return &guardrailPolicies{
		gentype.NewClientWithList[*apiv1alpha1.GuardrailPolicy, *apiv1alpha1.GuardrailPolicyList](
			"guardrailpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.GuardrailPolicy { return &apiv1alpha1.GuardrailPolicy{} },
			func() *apiv1alpha1.GuardrailPolicyList { return &apiv1alpha1.GuardrailPolicyList{} },
		),
	}
}
