// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1"
	apiv1alpha1 "github.com/envoyproxy/ai-gateway/api/v1alpha1/client/clientset/versioned/typed/api/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGuardrailPolicies implements GuardrailPolicyInterface
type fakeGuardrailPolicies struct {
	*gentype.FakeClientWithList[*v1alpha1.GuardrailPolicy, *v1alpha1.GuardrailPolicyList]
	Fake *FakeAigatewayV1alpha1
}

func newFakeGuardrailPolicies(fake *FakeAigatewayV1alpha1, namespace string) apiv1alpha1.GuardrailPolicyInterface {
	return &fakeGuardrailPolicies{
		gentype.NewFakeClientWithList[*v1alpha1.GuardrailPolicy, *v1alpha1.GuardrailPolicyList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("guardrailpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("GuardrailPolicy"),
			func() *v1alpha1.GuardrailPolicy { return &v1alpha1.GuardrailPolicy{} },
			func() *v1alpha1.GuardrailPolicyList { return &v1alpha1.GuardrailPolicyList{} },
			func(dst, src *v1alpha1.GuardrailPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.GuardrailPolicyList) []*v1alpha1.GuardrailPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.GuardrailPolicyList, items []*v1alpha1.GuardrailPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
