// Copyright Envoy AI Gateway Authors
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1"
	apiv1beta1 "github.com/envoyproxy/ai-gateway/api/v1beta1/client/clientset/versioned/typed/api/v1beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGuardrailPolicies implements GuardrailPolicyInterface
type fakeGuardrailPolicies struct {
	*gentype.FakeClientWithList[*v1beta1.GuardrailPolicy, *v1beta1.GuardrailPolicyList]
	Fake *FakeAigatewayV1beta1
}

func newFakeGuardrailPolicies(fake *FakeAigatewayV1beta1, namespace string) apiv1beta1.GuardrailPolicyInterface {
	return &fakeGuardrailPolicies{
		gentype.NewFakeClientWithList[*v1beta1.GuardrailPolicy, *v1beta1.GuardrailPolicyList](
			fake.Fake,
			namespace,
			v1beta1.SchemeGroupVersion.WithResource("guardrailpolicies"),
			v1beta1.SchemeGroupVersion.WithKind("GuardrailPolicy"),
			func() *v1beta1.GuardrailPolicy { return &v1beta1.GuardrailPolicy{} },
			func() *v1beta1.GuardrailPolicyList { return &v1beta1.GuardrailPolicyList{} },
			func(dst, src *v1beta1.GuardrailPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1beta1.GuardrailPolicyList) []*v1beta1.GuardrailPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1beta1.GuardrailPolicyList, items []*v1beta1.GuardrailPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
