# Copyright Envoy AI Gateway Authors
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIGatewayRoute
metadata:
  name: envoy-ai-gateway-basic-typesafe
  namespace: default
spec:
  parentRefs:
    - name: envoy-ai-gateway-basic
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: jev-latest
      backendRefs:
        - name: envoy-ai-gateway-basic-typesafe
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: AIServiceBackend
metadata:
  name: envoy-ai-gateway-basic-typesafe
  namespace: default
spec:
  schema:
    name: TypeSafe
    version: v1
  backendRef:
    name: envoy-ai-gateway-basic-typesafe
    kind: Backend
    group: gateway.envoyproxy.io
---
apiVersion: aigateway.envoyproxy.io/v1beta1
kind: BackendSecurityPolicy
metadata:
  name: envoy-ai-gateway-basic-typesafe-apikey
  namespace: default
spec:
  targetRefs:
    - group: aigateway.envoyproxy.io
      kind: AIServiceBackend
      name: envoy-ai-gateway-basic-typesafe
  type: APIKey
  apiKey:
    secretRef:
      name: envoy-ai-gateway-basic-typesafe-apikey
      namespace: default
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: envoy-ai-gateway-basic-typesafe
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: api.typesafe.ai
        port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: envoy-ai-gateway-basic-typesafe-tls
  namespace: default
spec:
  targetRefs:
    - group: "gateway.envoyproxy.io"
      kind: Backend
      name: envoy-ai-gateway-basic-typesafe
  validation:
    wellKnownCACertificates: "System"
    hostname: api.typesafe.ai
---
apiVersion: v1
kind: Secret
metadata:
  name: envoy-ai-gateway-basic-typesafe-apikey
  namespace: default
type: Opaque
stringData:
  apiKey: TYPESAFE_API_KEY # Replace with your TypeSafe API key.
